language: 
  - cpp
  - java
compiler:
  - gcc
  - clang
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
before_install:

  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libfltk1.3-dev fltk1.3; fi


branches:
  only:
    - master

os:
  - linux
  - osx
